version: '2'
services:
    booking-app:
        image: booking
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://booking-mysql:3306/booking?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=internal
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=internal
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://booking-elasticsearch:9200
    booking-mysql:
        extends:
            file: mysql.yml
            service: booking-mysql
    booking-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: booking-elasticsearch
